name: Create m3u file from URL

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the main branch

jobs:
  create-m3u:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Fetch m3u file from URL
      run: |
        wget -O Bjtech_fancode.m3u https://rattling-glazes.000webhostapp.com/Bjtech_fancode.m3u
      
    - name: Create m3u file
      run: |
        echo "File created from URL"  # Placeholder for any processing needed
        
    - name: Commit m3u file
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add Bjtech_fancode.m3u
        git commit -m "Automatically created m3u file"
        git push
        
