name: Update M3U Playlist

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch and update playlist
        run: ./update_playlist.sh
